import { readFile } from "node:fs/promises";
import path from "node:path";
import { NextResponse } from "next/server";
import type { DeployedToken } from "../../../../config/deployedTokens";

// deployed-tokens.json is generated by `npm run deploy:tokens` at the repo
// root (one level up from frontend/). Read it server-side on each request
// so the frontend always reflects the latest deployment without a rebuild.
const tokensPath = path.join(process.cwd(), "..", "deployed-tokens.json");

export async function GET() {
  let raw: string;
  try {
    raw = await readFile(tokensPath, "utf-8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return NextResponse.json({ tokens: [], seeded: false });
    }
    console.error(`Failed to read ${tokensPath}:`, error);
    return NextResponse.json(
      { tokens: [], seeded: false, error: "deployed-tokens.json exists but could not be read." },
      { status: 500 },
    );
  }

  try {
    const tokens: Record<string, DeployedToken> = JSON.parse(raw);
    return NextResponse.json({ tokens: Object.values(tokens), seeded: true });
  } catch (error) {
    console.error(`Failed to parse ${tokensPath}:`, error);
    return NextResponse.json(
      { tokens: [], seeded: false, error: "deployed-tokens.json is not valid JSON." },
      { status: 500 },
    );
  }
}
