import { readFile } from "node:fs/promises";
import path from "node:path";
import { NextResponse } from "next/server";

export interface DeployedToken {
  address: string;
  name: string;
  symbol: string;
}

// deployed-tokens.json is generated by `npm run deploy:tokens` at the repo
// root (one level up from frontend/). Read it server-side on each request
// so the frontend always reflects the latest deployment without a rebuild.
export async function GET() {
  const tokensPath = path.join(process.cwd(), "..", "deployed-tokens.json");

  try {
    const raw = await readFile(tokensPath, "utf-8");
    const tokens: Record<string, DeployedToken> = JSON.parse(raw);
    return NextResponse.json({ tokens: Object.values(tokens), seeded: true });
  } catch {
    return NextResponse.json({ tokens: [], seeded: false });
  }
}
